### ISSUE TITLE
[ compat ] library no longer builds against Idris HEAD

### ISSUE THREAD

**Issue by stefan-hoeck** [kbertalan/idris2-go#2]
The reason seems to be the introduction of the `(|>)` operator in the Prelude.

**Comment by kbertalan** [comment]
I am quite dependent on pack itself to run my projects, so it is quite a pain to setup an Idris2 HEAD without it.
Because of this I have made a guess for the fix, and ignored the `Prelude.Basics.(|>)` and `Prelude.Ops.infixl.(|>)` in every file where I am using that operator.

If this turns out to be good and enables creating a new pack collection, then I will be able to migrate to the operator defined in Prelude and remove my version.

**Comment by kbertalan** [comment]
This project has been built and tested properly in the last run of pack-db, see https://github.com/stefan-hoeck/idris2-pack-db/actions/runs/9433923106/job/25985421554

Now waiting for the next pack collection to include the latest idris2 version.

**Comment by stefan-hoeck** [comment]
I tested this locally and all seems to be well. We still have some other issues (unrelated to your libraries) in the pack-db, but I hope to get a new nightly tonight.

**Comment by stefan-hoeck** [comment]
> I am quite dependent on pack itself to run my projects, so it is quite a pain to setup an Idris2 HEAD without it. Because of this I have made a guess for the fix, and ignored the `Prelude.Basics.(|>)` and `Prelude.Ops.infixl.(|>)` in every file where I am using that operator.
> 
> If this turns out to be good and enables creating a new pack collection, then I will be able to migrate to the operator defined in Prelude and remove my version.

Here is the workflow I use to test failing packages against the latest HEAD of Idris:

Install `pack-admin`:

```sh
pack install-app pack-admin
```

Generate a new pack collection from the latest Git commits:

```sh
pack-admin extract-from-head test.toml
```

Move the generated `.toml` file  to the `db` folder of pack's install directors (as a default, this is in folder `$HOME/.pack`):

```sh
mv test.toml $HOME/.pack/db/test.toml
```

(feel free to use another name than `test.toml`). Now, switch the pack collection to the newly generated one:

```sh
pack switch test
```

You have now setup pack with the latest version of Idris and can use this to compile and test your failing libraries. You can use `pack switch` to switch to another (stable) version of the pack collection any time.

**Comment by kbertalan** [comment]
Thanks for the description.

I have run into issues at the `pack-admin extract-from-head test.toml`, what I worked around by copying the latest working nightly toml to another file and replace the Idris2 commit hash to the latest one. After it I could switch to that collection and make my final changes.

So I managed to migrate to the `(|>)` operator in Prelude.

**Comment by kbertalan** [comment]
Changes are now included into the latest pack-db collection, see results of https://github.com/stefan-hoeck/idris2-pack-db/actions/runs/9439497744/job/25997698037
